# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: howtoguy.tv
email: glen@howtoguy.tv
description: > # this means to ignore newlines until "baseurl:"
  Howtoguy knows everything. Howtoguy can teach you how to do anything. Need to know how to test and replace a condensor on a '77 Kawasaki 650 motorcycle or build a wordpress website? Howtoguy has you covered.
baseurl: "" # the subpath of your site, e.g. /blog
url: "howtoguy.github.io" # the base hostname & protocol for your site
twitter_username: fotozfotoz
github_username:  howtoguy
port: 4001

# Build settings
markdown: kramdown
